[tool.black]
line-length = 79
target-version = ['py36']
skip-string-normalization = true

[tool.pylint.messages_control]
disable = "bad-continuation"

[tool.pylint.reports]
output-format = "colorized"
